[server]
host = "0.0.0.0"
port = 8080
enable_cors = true
cors_origins = ["*"]

[logging]
level = "info"
format = "pretty"

[health_check]
interval_seconds = 30
timeout_seconds = 10
max_failures = 3

[security]
enable_auth = false
api_key = ""
rate_limit_per_minute = 1000

[network]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
denied_cidrs = []
deny_action = "reject"
trust_proxy_headers = true
