# ScoutQuest Server Configuration - Development with TLS
# This example shows development-friendly TLS configuration

[server]
host = "127.0.0.1"
port = 8443
enable_cors = true
cors_origins = ["*"]

[logging]
level = "debug"
format = "pretty"

[health_check]
interval_seconds = 60
timeout_seconds = 15
max_failures = 5

[security]
enable_auth = false
rate_limit_per_minute = 10000

# TLS Configuration - Development
[tls]
# Enable TLS/HTTPS support
enabled = true

# Certificate directory (local development)
cert_dir = "./dev-certs"

# Auto-generate self-signed certificates
auto_generate = true

# Disable peer verification for development
verify_peer = false

# TLS protocol versions
min_version = "1.2"
max_version = "1.3"

# No HTTP redirect for development
redirect_http = false
