name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main, develop, release/** ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Dependencies
        run: |
          pnpm install
          cd scoutquest-js && pnpm install
          cd ../examples/js && pnpm install

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            scoutquest-server/target
            scoutquest-rust/target
            examples/rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Lint and Format Check
        run: |
          # Rust formatting and linting
          cd scoutquest-server && cargo fmt -- --check
          cd ../scoutquest-rust && cargo fmt -- --check
          cd ../scoutquest-server && cargo clippy -- -D warnings
          cd ../scoutquest-rust && cargo clippy -- -D warnings

          # JavaScript linting
          cd ../scoutquest-js && pnpm run lint

      - name: Run Tests
        run: make test-setup

      - name: Build All Components
        run: make build-all

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            scoutquest-server/target/release/scoutquest-server
            scoutquest-js/dist/
          retention-days: 7
